#!/usr/bin/env python
"""Binary clock example using BlinkyTape.py

Displays UNIX epoch time using 32 LEDs (white),
  localtime hours using 6 LEDs (red),
  localtime minutes using 6 LEDs (green),
  localtime seconds using 6 LEDs (blue)
"""
import optparse
import time
from BlinkyTape import BlinkyTape
from datetime import datetime

BRIGHTNESS = 50  # in range(255)


def display(bt):
    dt = datetime.now()
    send_binary(int(time.time()), 32, bt, BRIGHTNESS, BRIGHTNESS, BRIGHTNESS)
    send_binary(dt.hour, 6, bt, BRIGHTNESS, 0, 0)
    send_binary(dt.minute, 6, bt, 0, BRIGHTNESS, 0)
    send_binary(dt.second, 6, bt, 0, 0, BRIGHTNESS)
    send_binary(0, 10, bt, 0, 0, 0)  # padding empty pixels - can add more info
    bt.show()


def send_binary(word, length, bt, r, g, b):
    fmt = "{0:0" + str(length) + "b}"
    array = list(fmt.format(word))
    for bit in array:
        bt.sendPixel(r * int(bit), g * int(bit), b * int(bit))


parser = optparse.OptionParser()
parser.add_option("-p", "--port", dest="portname",
                  help="serial port (ex: /dev/ttyUSB0)", default=None)
options, args = parser.parse_args()

if options.portname is not None:
    port = options.portname
else:
    print "Usage: python binary_clock.py -p <port name>"
    print "(ex: python binary_clock.py -p /dev/ttypACM0)"
    exit()

bt = BlinkyTape(port)

# roughly synchronize with seconds
time.sleep(1 - datetime.now().microsecond / 1000000.0)

while True:
    timeBegin = time.time()

    display(bt)

    timeEnd = time.time()
    timeElapsed = timeEnd - timeBegin
    time.sleep(1 - timeElapsed)
